FROM golang:1.20 AS builder

WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o app .

FROM gcr.io/distroless/static

WORKDIR /root/
COPY --from=builder /app/app .
COPY --from=builder /app/templates ./templates

ENTRYPOINT ["/root/app"]
CMD ["serve"]
