FROM golang:1.20-alpine AS builder

WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM scratch

WORKDIR /root/
COPY --from=builder /app/app .
COPY --from=builder /app/templates ./templates

ENTRYPOINT ["/root/app"]
CMD ["serve"]
